# Generated by Django 4.2.9 on 2024-02-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0004_asset_alloted_to_asset_current_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettype',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asset_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_allocation_status',
            field=models.CharField(choices=[('UNALLOCATED', 'Unallocated'), ('ALLOCATED', 'Allocated')], default='UNALLOCATED', max_length=15),
        ),
    ]
