# Generated by Django 4.2.9 on 2024-02-05 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0005_asset_created_by_assettype_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_types_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
