# Generated by Django 4.2.9 on 2024-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0008_asset_created_by_assettype_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_allocation_status',
            field=models.CharField(choices=[('UNALLOCATED', 'Unallocated'), ('ALLOCATED', 'Allocated')], default='UNALLOCATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='type',
            field=models.TextField(),
        ),
    ]
