# Generated by Django 4.2.9 on 2024-02-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0009_alter_asset_current_allocation_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together={('type', 'created_by')},
        ),
    ]
